########################################
# LOGBACK CONFIG
########################################
logging:
  level:
    root: info
    org: info
    sunghs: info
  file:
    name: /logs/sniff.log
    max-size: 100MB
    max-history: 1

########################################
# KAFKA CONFIG
########################################

########################################
# DATASOURCE CONFIG
########################################


########################################
# SNIFF CUSTOM CONFIG
########################################
sniff:
  listen:
    ip: 192.168.200.101
    required-data: true
    auto-scan: true
    capture-level: ethernet
    capture-type: http
    hex-to-string: true

########################################
# THREAD CONFIG
########################################
thread:
  producer:
    prefix: producer
    core-pool-size: 10
    max-pool-size: 50
    capacity: 100
  consumer:
    prefix: consumer
    core-pool-size: 10
    max-pool-size: 50
    capacity: 100