########################################
# SPRING CONFIG
########################################
spring:
  application:
    name: packet-sniffer
  profiles:
    active: local
  ########################################
  # JPA CONFIG
  ########################################
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
  ########################################
  # DATABASE CONFIG
  ########################################
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:10000/packet?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
    username: root
    password: password
    hikari:
      connection-test-query: select 1 from dual
      pool-name: sniff-dbcp
      minimum-idle: 1
      maximum-pool-size: 10
      validation-timeout: 10000
      auto-commit: true
      connection-timeout: 20000
      idle-timeout: 200000
      max-lifetime: 1200000
  ########################################
  # KAFKA CONFIG
  ########################################
  kafka:
    bootstrap-servers: localhost:10001
    template:
      default-topic: packet
    producer:
      retries: 3
      bootstrap-servers: localhost:10001
    consumer:
      group-id: consumer-1
      auto-offset-reset: latest
      enable-auto-commit: true
      max-poll-records: 1000
      auto-commit-interval: 10s
      bootstrap-servers: localhost:10001
########################################
# LOGBACK CONFIG
########################################
logging:
  level:
    root: info
    org: info
    sunghs: debug
  file:
    path: ${user.home}/pc
    name: ${spring.application.name}.log
    max-size: 100MB
    max-history: 1
########################################
# THREAD CONFIG
########################################
thread:
  producer:
    prefix: producer
    core-pool-size: 10
    max-pool-size: 50
    capacity: 10000
  consumer:
    prefix: consumer
    core-pool-size: 1
    max-pool-size: 1
    capacity: 10000
########################################
# SNIFF CUSTOM CONFIG
########################################
sniff:
  listen:
    ip: 10.200.195.98
    required-data: true
    auto-scan: true
    capture-level: ethernet
    capture-type: http
    hex-to-string: true
