########################################
# SPRING CONFIG
########################################
spring:
  application:
    name: packet-sniffer
  jpa:
    database: mysql
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
  datasource:
    dbcp2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:10000/packet?useUnicode=true&characterEncoding=utf-8
      username: root
      password: password
      initial-size: 1
      min-idle: 3
      max-idle: 3
      max-total: 3
      validation-query: select 1 from dual
      min-evictable-idle-time-millis: 12000
      time-between-eviction-runs-millis: 60000
      test-while-idle: true
      test-on-borrow: true
  task:
    execution:
      thread-name-prefix: hs
########################################
# LOGBACK CONFIG
########################################
logging:
  level:
    root: info
    org: info
    sunghs: info
  file:
    path: ${user.home}/pc
    name: ${spring.application.name}.log
    max-size: 100MB
    max-history: 1
########################################
# KAFKA CONFIG
########################################

########################################
# SNIFF CUSTOM CONFIG
########################################
sniff:
  listen:
    ip: 192.168.200.101
    required-data: true
    auto-scan: false
    capture-level: ethernet
    capture-type: http
    hex-to-string: true
