########################################
# LOGBACK CONFIG
########################################
logging:
  level:
    org: info
    sunghs: info
  file:
    name: /logs/sniff.log
    max-size: 100MB
    max-history: 1

########################################
# KAFKA CONFIG
########################################

########################################
# DATASOURCE CONFIG
########################################


########################################
# SNIFF CUSTOM CONFIG
########################################
sniff:
  listen:
    ip: 127.0.0.1
    required-data: true
    auto-scan: false
    capture-level: ethernet

########################################
# THREAD CONFIG
########################################
thread:
  producer:
    prefix: producer
    core-pool-size: 10
    max-pool-size: 50
    capacity: 100
  consumer:
    prefix: consumer
    core-pool-size: 10
    max-pool-size: 50
    capacity: 100