########################################
# LOGBACK CONFIG
########################################
logging:
  level:
    org: info
    sunghs: debug
  file:
    name: /logs/sniff.log
    max-size: 100MB
    max-history: 1

########################################
# KAFKA CONFIG
########################################

########################################
# DATASOURCE CONFIG
########################################


########################################
# SNIFF CUSTOM CONFIG
########################################
sniff:
  listen:
    ip: 172.0.0.1
    index: 0

########################################
# THREAD CONFIG
########################################
thread:
  producer:
    prefix: producer
    core-pool-size: 10
    max-pool-size: 50
    capacity: 100
  consumer:
    prefix: consumer
    core-pool-size: 10
    max-pool-size: 50
    capacity: 100