########################################
# LOGBACK CONFIG
########################################
logging:
  level:
    org: info
    sunghs: info
  file:
    name: /logs/sniff.log
    max-size: 100MB
    max-history: 1

########################################
# KAFKA CONFIG
########################################

########################################
# DATASOURCE CONFIG
########################################